# .github/workflows/deploy.yml
name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
        
      - name: Read configuration
        id: config
        run: |
          echo "SOURCE_USERNAME=$(yq e '.sourceOrg.username' config.yml)" >> $GITHUB_ENV
          echo "SOURCE_PASSWORD=$(yq e '.sourceOrg.password' config.yml)" >> $GITHUB_ENV
          echo "SOURCE_URL=$(yq e '.sourceOrg.url' config.yml)" >> $GITHUB_ENV
          echo "TARGET_USERNAME=$(yq e '.targetOrg.username' config.yml)" >> $GITHUB_ENV
          echo "TARGET_PASSWORD=$(yq e '.targetOrg.password' config.yml)" >> $GITHUB_ENV
          echo "TARGET_URL=$(yq e '.targetOrg.url' config.yml)" >> $GITHUB_ENV

      - name: Install Salesforce CLI
        run: |
            sudo npm install -g sfdx-cli


      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -u $SOURCE_USERNAME -p path/to/source
          sfdx force:source:deploy -u $TARGET_USERNAME -p path/to/target

